# -*- coding: utf-8 -*-
"""Visualisation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c5HxNdj5w9BNVMo_zVo27kXiIDMwr0c8
"""

!pip install streamlit pandas
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!sudo dpkg -i cloudflared-linux-amd64.deb
!pip install streamlit-folium folium

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import plotly.express as px
# import requests
# import time
# from streamlit_folium import st_folium
# 
# st.set_page_config(page_title="CSV Dashboard", layout="wide")
# st.title("CSV Dashboard")
# 
# # ----------------------------
# # MULTIPLE FILE UPLOAD
# # ----------------------------
# uploaded_files = st.file_uploader("Upload CSV files", type=["csv"], accept_multiple_files=True)
# 
# if uploaded_files:
#     # Dictionary to store uploaded DataFrames
#     dataframes = {f.name: pd.read_csv(f) for f in uploaded_files}
# 
#     # Dropdown to select which file to analyze
#     selected_file = st.selectbox("Select file to analyze", list(dataframes.keys()))
#     df = dataframes[selected_file]
# 
#     st.write(f"### Selected file: {selected_file} ({len(df)} records)")
# 
#     # ----------------------------
#     # RECORD SELECTOR
#     # ----------------------------
#     st.subheader("Select Number of Records")
#     record_options = ["All Data", 10, 50, 100, 500, 1000, "Custom"]
#     record_choice = st.selectbox("How many rows to analyze?", record_options)
# 
#     if record_choice == "All Data":
#         df_filtered = df.copy()
#     elif record_choice == "Custom":
#         custom_n = st.number_input(
#             "Enter number of rows:", min_value=1, max_value=len(df), value=len(df)
#         )
#         df_filtered = df.head(int(custom_n))
#     else:
#         df_filtered = df.head(int(record_choice))
# 
#     st.write(f"### Showing {len(df_filtered)} of {len(df)} records")
#     st.dataframe(df_filtered)
#     df = df_filtered
# 
#     st.markdown("---")
#     st.header("Bar Charts")
# 
#     # Bar chart columns
#     col_x = st.selectbox("X-axis (categorical)", df.columns, key="bar_x")
#     col_y = st.selectbox("Y-axis (numeric)", df.columns, key="bar_y")
# 
#     chart_type = st.selectbox(
#         "Bar Chart Type",
#         ["Vertical Bar", "Horizontal Bar", "Grouped Bar", "Stacked Bar"]
#     )
# 
#     # -----------------------------------------
#     # FIXED: PLOTTING EXACT VALUES (NO AUTO AGGREGATION)
#     # -----------------------------------------
#     df_plot = df.copy()
# 
#     # If y column is non-numeric, convert safely
#     if not np.issubdtype(df_plot[col_y].dtype, np.number):
#         try:
#             df_plot[col_y] = pd.to_numeric(df_plot[col_y], errors="coerce")
#         except:
#             st.error("Y-axis column must be numeric for bar charts.")
#             st.stop()
# 
#     # ---------------------------
#     # INTERACTIVE PLOTLY BAR CHARTS
#     # ---------------------------
#     if chart_type == "Vertical Bar":
#         fig = px.bar(df_plot, x=col_x, y=col_y)
#         fig.update_layout(title="Vertical Bar Chart", xaxis_title=col_x, yaxis_title=col_y, xaxis_tickangle=-45)
#         st.plotly_chart(fig, use_container_width=True)
# 
#     elif chart_type == "Horizontal Bar":
#         fig = px.bar(df_plot, x=col_y, y=col_x, orientation='h')
#         fig.update_layout(title="Horizontal Bar Chart", xaxis_title=col_y, yaxis_title=col_x)
#         st.plotly_chart(fig, use_container_width=True)
# 
#     elif chart_type == "Grouped Bar":
#         group_col = st.selectbox("Grouping Column", df.columns, key="groupbar")
#         fig = px.bar(df_plot, x=col_x, y=col_y, color=group_col, barmode="group")
#         fig.update_layout(title="Grouped Bar Chart", xaxis_tickangle=-45)
#         st.plotly_chart(fig, use_container_width=True)
# 
#     elif chart_type == "Stacked Bar":
#         stack_col = st.selectbox("Stack Column", df.columns, key="stackbar")
#         fig = px.bar(df_plot, x=col_x, y=col_y, color=stack_col, barmode="stack")
#         fig.update_layout(title="Stacked Bar Chart", xaxis_tickangle=-45)
#         st.plotly_chart(fig, use_container_width=True)
# 
#     # ---------------------------
#     # HEATMAPS
#     # ---------------------------
#     st.markdown("---")
#     st.header("Heatmaps (Seaborn)")
#     heatmap_type = st.selectbox("Choose Heatmap Type", ["Correlation Heatmap", "Pivot Heatmap"])
# 
#     if heatmap_type == "Correlation Heatmap":
#         numeric_df = df.select_dtypes(include=[np.number])
#         if numeric_df.shape[1] >= 2:
#             corr = numeric_df.corr()
#             fig, ax = plt.subplots(figsize=(10, 6))
#             sns.heatmap(corr, annot=True, cmap="coolwarm", ax=ax)
#             st.pyplot(fig)
#         else:
#             st.warning("Need at least 2 numeric columns.")
#     else:
#         x_col = st.selectbox("X-axis", df.columns)
#         y_col = st.selectbox("Y-axis", df.columns)
#         val_col = st.selectbox("Value (numeric)", df.columns)
#         try:
#             pivot = df.pivot_table(index=y_col, columns=x_col, values=val_col, aggfunc="mean")
#             fig, ax = plt.subplots(figsize=(10, 6))
#             sns.heatmap(pivot, annot=True, cmap="viridis", ax=ax)
#             st.pyplot(fig)
#         except:
#             st.error("Could not create pivot table. Choose valid columns.")
# 
#     # ---------------------------
#     # MAP PLOT (ORIGINAL)
#     # ---------------------------
#     st.markdown("---")
#     st.header("🗺 Basic Map Plot")
#     if "lat" in df.columns and "lon" in df.columns:
#         st.map(df[["lat", "lon"]])
#     else:
#         st.info("CSV must include 'lat' & 'lon' columns to render a map. Skipping...")

import subprocess, threading, time

def run_streamlit():
    subprocess.run(["streamlit", "run", "app.py", "--server.port", "8501"])

threading.Thread(target=run_streamlit).start()
time.sleep(5)

!cloudflared tunnel --url http://localhost:8501 --no-autoupdate

